# Dart 代码分析器配置文件
# 用于静态分析代码，检查错误、警告和代码规范问题
# 分析结果会在 IDE 中显示，也可通过命令行运行 `flutter analyze` 查看

# 引入 Flutter 推荐的代码规范规则集
include: package:flutter_lints/flutter.yaml

# 代码规范规则配置
linter:
  # 可以在此处自定义规则：
  # - 禁用某些规则：将规则设置为 false
  # - 启用额外规则：将规则设置为 true
  # 所有可用规则文档：https://dart.dev/lints
  #
  # 如果只想在特定代码行禁用规则，可以使用：
  # // ignore: rule_name        - 忽略单行
  # // ignore_for_file: rule_name - 忽略整个文件
  rules:
    # 示例：禁用避免使用 print 的规则
    # avoid_print: false
    # 示例：启用优先使用单引号的规则
    # prefer_single_quotes: true

# 更多配置信息：https://dart.dev/guides/language/analysis-options
