# Codemagic CI/CD 自动化构建配置文件
# 用于配置自动化构建、测试和发布流程

workflows:
  # iOS 构建工作流
  ios-workflow:
    name: iOS Workflow
    # 最大构建时长（分钟）
    max_build_duration: 120
    # 使用的构建实例类型
    instance_type: mac_mini_m1
    
    # 环境配置
    environment:
      # 环境变量组（如需要 API 密钥等敏感信息）
      groups:
        # 示例：App Store Connect 凭证组
        # - app_store_credentials
      
      # 环境变量
      vars:
        # Xcode 工作空间路径
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        # Xcode 构建方案名称
        XCODE_SCHEME: "Runner"
        # Flutter SDK 版本
        FLUTTER_VERSION: "3.35.7"
      
      # 工具版本配置
      flutter: stable
      xcode: latest
      cocoapods: default
    
    # 构建脚本步骤
    scripts:
      # 步骤1: 获取 Flutter 依赖包
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      
      # 步骤2: 生成应用图标
      - name: Generate app icons
        script: |
          flutter pub run flutter_launcher_icons
      
      # 步骤3: 清理和配置 CocoaPods（解决 CDN 和缓存问题）
      - name: Setup CocoaPods
        script: |
          # 设置环境变量，禁用 CDN
          export COCOAPODS_CDN_TRUNK_URL=""
          export COCOAPODS_DISABLE_STATS=1
          
          # 清理 CocoaPods 缓存
          pod cache clean --all || true
          
          # 清理旧的仓库（包括可能存在的 CDN 仓库）
          pod repo remove trunk || true
          pod repo remove master || true
          
          # 直接使用 GitHub 镜像（CDN 持续失败）
          echo "使用 GitHub 镜像作为 CocoaPods 仓库..."
          pod repo add trunk https://github.com/CocoaPods/Specs.git
          
          # 验证仓库已添加
          if pod repo list | grep -q trunk; then
            echo "✅ CocoaPods 仓库添加成功"
            pod repo list
          else
            echo "❌ CocoaPods 仓库添加失败"
            exit 1
          fi
          
          # 更新仓库（使用 GitHub 镜像）- 这可能需要一些时间
          echo "更新 CocoaPods 仓库（这可能需要几分钟）..."
          timeout 300 pod repo update trunk || echo "仓库更新超时或失败，但继续..."
      
      # 步骤4: 安装 CocoaPods 依赖（iOS 原生依赖管理）
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          
          # 删除旧的 Pods 和锁定文件
          rm -rf Pods Podfile.lock
          
          # 设置环境变量，禁用 CDN
          export COCOAPODS_DISABLE_STATS=1
          export COCOAPODS_CDN_TRUNK_URL=""
          
          # 确保 trunk 仓库存在且指向 GitHub
          echo "检查 CocoaPods 仓库状态..."
          if ! pod repo list | grep -q "trunk.*github.com"; then
            echo "仓库不存在或指向错误，重新添加..."
            pod repo remove trunk || true
            pod repo add trunk https://github.com/CocoaPods/Specs.git
          fi
          
          # 验证仓库
          echo "当前仓库列表："
          pod repo list
          
          # 使用 --no-repo-update 安装（避免尝试访问 CDN）
          echo "开始安装 CocoaPods 依赖（使用 --no-repo-update）..."
          pod install --no-repo-update || {
            echo "安装失败，检查错误..."
            echo "仓库状态："
            pod repo list
            echo "尝试使用普通安装..."
            pod install || {
              echo "❌ CocoaPods 安装失败"
              exit 1
            }
          }
          
          echo "✅ CocoaPods 依赖安装成功"
          cd ..
      
      # 步骤5: 构建 iOS IPA 安装包
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
    
    # 构建产物（构建完成后保留的文件）
    artifacts:
      # IPA 安装包
      - build/ios/ipa/*.ipa
      # Xcode 构建日志
      - /tmp/xcodebuild_logs/*.log
      # Flutter 驱动测试日志
      - flutter_drive.log
    
    # 发布配置
    publishing:
      # 邮件通知配置
      email:
        recipients:
          # 接收通知的邮箱地址
          - Stringuo@163.com
        notify:
          # 构建成功时发送邮件
          success: true
          # 构建失败时不发送邮件
          failure: false
      
      # App Store Connect 自动上传配置（当前未启用）
      app_store_connect:
        # 如需自动上传到 App Store Connect，取消以下注释并配置
        # auth: integration
        # submit_to_testflight: false
        # beta_groups:
        #   - group name 1
        #   - group name 2
