# Codemagic CI/CD 自动化构建配置文件
# 用于配置自动化构建、测试和发布流程

workflows:
  # iOS 构建工作流
  ios-workflow:
    name: iOS Workflow
    # 最大构建时长（分钟）
    max_build_duration: 120
    # 使用的构建实例类型
    instance_type: mac_mini_m1
    
    # 环境配置
    environment:
      # 环境变量组（如需要 API 密钥等敏感信息）
      groups:
        # 示例：App Store Connect 凭证组
        # - app_store_credentials
      
      # 环境变量
      vars:
        # Xcode 工作空间路径
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        # Xcode 构建方案名称
        XCODE_SCHEME: "Runner"
        # Flutter SDK 版本
        FLUTTER_VERSION: "3.35.7"
      
      # 工具版本配置
      flutter: stable
      xcode: latest
      cocoapods: default
    
    # 构建脚本步骤
    scripts:
      # 步骤1: 获取 Flutter 依赖包
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      
      # 步骤2: 生成应用图标
      - name: Generate app icons
        script: |
          flutter pub run flutter_launcher_icons
      
      # 步骤3: 清理和配置 CocoaPods（解决 CDN 和缓存问题）
      - name: Setup CocoaPods
        script: |
          # 清理 CocoaPods 缓存
          pod cache clean --all || true
          
          # 清理旧的仓库
          pod repo remove trunk || true
          
          # 尝试添加 CDN 仓库
          pod repo add trunk https://cdn.cocoapods.org/ || true
          
          # 如果 CDN 失败，尝试使用 GitHub 镜像
          if ! pod repo list | grep -q trunk; then
            echo "CDN 失败，尝试使用 GitHub 镜像..."
            pod repo add trunk https://github.com/CocoaPods/Specs.git || true
          fi
          
          # 更新仓库（如果可能）
          pod repo update trunk || true
      
      # 步骤4: 安装 CocoaPods 依赖（iOS 原生依赖管理）
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          
          # 删除旧的 Pods 和锁定文件
          rm -rf Pods Podfile.lock
          
          # 设置环境变量，禁用 CDN（如果 CDN 有问题）
          export COCOAPODS_DISABLE_STATS=1
          
          # 尝试安装，使用多种策略
          set +e  # 允许错误继续
          
          # 策略1: 使用 --repo-update
          pod install --repo-update
          POD_INSTALL_STATUS=$?
          
          # 策略2: 如果不更新仓库
          if [ $POD_INSTALL_STATUS -ne 0 ]; then
            echo "策略1失败，尝试不使用仓库更新..."
            pod install --no-repo-update
            POD_INSTALL_STATUS=$?
          fi
          
          # 策略3: 清理缓存后重试
          if [ $POD_INSTALL_STATUS -ne 0 ]; then
            echo "策略2失败，清理缓存后重试..."
            pod cache clean --all || true
            pod install --no-repo-update
            POD_INSTALL_STATUS=$?
          fi
          
          # 策略4: 最后尝试普通安装
          if [ $POD_INSTALL_STATUS -ne 0 ]; then
            echo "策略3失败，尝试普通安装..."
            pod install
            POD_INSTALL_STATUS=$?
          fi
          
          set -e  # 恢复错误检查
          
          # 如果所有策略都失败，退出
          if [ $POD_INSTALL_STATUS -ne 0 ]; then
            echo "所有 CocoaPods 安装策略都失败了"
            exit 1
          fi
          
          cd ..
      
      # 步骤5: 构建 iOS IPA 安装包
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
    
    # 构建产物（构建完成后保留的文件）
    artifacts:
      # IPA 安装包
      - build/ios/ipa/*.ipa
      # Xcode 构建日志
      - /tmp/xcodebuild_logs/*.log
      # Flutter 驱动测试日志
      - flutter_drive.log
    
    # 发布配置
    publishing:
      # 邮件通知配置
      email:
        recipients:
          # 接收通知的邮箱地址
          - Stringuo@163.com
        notify:
          # 构建成功时发送邮件
          success: true
          # 构建失败时不发送邮件
          failure: false
      
      # App Store Connect 自动上传配置（当前未启用）
      app_store_connect:
        # 如需自动上传到 App Store Connect，取消以下注释并配置
        # auth: integration
        # submit_to_testflight: false
        # beta_groups:
        #   - group name 1
        #   - group name 2
